<a href="https://colab.research.google.com/github/fightmeat/Machine_Leaning/blob/main/14_%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터(Data)
1. 통계분석은 데이터를 다루는 것이므로 데이터에서 본질적인 의미를 찾는다.
2. 변수의 종류
- 질적 변수 : 2진 변수라고도 부른다. 남성과 여성, 흡연 여부 등 값이 2개뿐인 변수로 명의 척도와 순서 척도가 있다.
- 양적 변수 : 양을 표현하는 변수, 간격 척도와 비례 척도가 있다.
- 이산형 변수 : 0,1,2... 와 같이 하나하나의 값을 취하는 변수로 서로 인접한 숫자 사이에 값이 존재하지 않는다.
- 연속형 변수 : 연속적인 값을 취할 수 있는 변수로 어떤 숫자 사이에도 반드시 숫자가 존재한다.

In [1]:
import numpy as np
import pandas as pd

- 매직 명령어(Magic Command) : IPython(Jupyter notebook) 시스템에서 제공하는 add_function
- 접두사 %의 경우 : 한 줄의 코드에서만 실행
- 접두사 %%의 경우 : 여러 줄, 즉 한 셀의 내용 전체를 실행

In [9]:
%%writefile sport_test.csv
학생번호,학년,악력,윗몸일으키기,점수,순위
1,1,40.2,34,15,4
2,1,34.2,14,7,10
3,1,28.8,27,11,7
4,2,39.0,27,14,5
5,2,50.9,32,17,2
6,2,36.5,20,9,9
7,3,36.6,31,13,6
8,3,49.2,37,18,1
9,3,26.0,28,10,8
10,3,47.4,32,16,3

Overwriting sport_test.csv


In [10]:
# index_col : 인덱스로 사용할 컬럼명
df = pd.read_csv('sport_test.csv', index_col='학생번호')

In [11]:
df

학년    악력  윗몸일으키기  점수  순위
학생번호                          
1      1  40.2      34  15   4
2      1  34.2      14   7  10
3      1  28.8      27  11   7
4      2  39.0      27  14   5
5      2  50.9      32  17   2
6      2  36.5      20   9   9
7      3  36.6      31  13   6
8      3  49.2      37  18   1
9      3  26.0      28  10   8
10     3  47.4      32  16   3

In [12]:
df['악력']

학생번호
1     40.2
2     34.2
3     28.8
4     39.0
5     50.9
6     36.5
7     36.6
8     49.2
9     26.0
10    47.4
Name: 악력, dtype: float64

# 데이터의 크기
- DataFrame의 크기는 shape

In [13]:
df.shape

(10, 5)

# 기초 통계 분석
- 데이터의 특징을 파악하는 방법에는 크게 두 가지가 있다.
- 하나는 평균이나 분산등의 수치지표에 따라 데이터를 요약하는 방법이고,
- 다른 하나는 그래프를 이용하여 시각화를 통해 데이터를 분석하는 방법이다.

In [19]:
# 출력된 소수점자리수를 제한하는 매직명령어
%precision 3
# DataFrame의 출력될 값의 소숫점이하 3자리로 제한
# pd.set_option('precision', 3)

'%.3f'

In [16]:
# numpy를 통해 소숫점 자릿수를 제한
np.set_printoptions(precision=3)

In [17]:
pd.options.display.float_format = '{:.3f}'.format

In [18]:
# numpy 실수 출력을 설정
np.set_printoptions(formatter={'float_kind':lambda x:"{0:0.3f}".format(x)})

In [20]:
%%writefile scores_em.csv
student_number,english,mathematics
1,42,65
2,69,80
3,56,63
4,41,63
5,57,76

Writing scores_em.csv


In [21]:
df2 = pd.read_csv('scores_em.csv', index_col='student_number')
df2

english  mathematics
student_number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [23]:
scores = np.array(df2['english'])
scores

array([42, 69, 56, 41, 57])

In [24]:
scores_df = pd.DataFrame({'score':scores},
                         index=pd.Index(['A','B','C','D','E']))
scores_df

score
A     42
B     69
C     56
D     41
E     57

## 평균값(mean) : 가장 일반적으로 사용되는 대푯값

In [25]:
sum(scores)/len(scores)

53.0

In [27]:
scores.mean()

53.0

In [28]:
np.mean(scores)

53.0

In [29]:
# DataFrame, Series객체에서 mean() 사용
scores_df.mean()

score   53.000
dtype: float64

In [31]:
scores_df['score'].mean() # 시리즈도 mean함수를 쓸수있다.

53.0

# 중앙값(median) : 데이터를 크기 순서대로 나열할 때 정확하게 중앙에 위치한 값

In [34]:
sorted_df = np.sort(df['윗몸일으키기'])
sorted_df

array([14, 20, 27, 27, 28, 31, 32, 32, 34, 37])

In [36]:
# 중앙값을 구현하는 함수 정의
n = len(sorted_df)
if n % 2 == 0:
  m0 = sorted_df[n // 2 - 1]
  m1 = sorted_df[n // 2]
  median = (m0 + m1)/2

else:
  median = sorted_df[(n+1)//2 -1]

print(median)

29.5


In [38]:
#numpy
np.median(sorted_df)

29.5

In [40]:
# DataFrame, Seriees : 객체명.median()
df['윗몸일으키기'].median()

29.5

## 최빈값(mode) : 데이터에서 가장 많이 나타나는 값
- 기본적으로 질적 데이터(범주형 데이터)의 대푯값을 구할 때 사용하는 지표

In [41]:
pd.Series([1,1,1,2,2,3,3,3,3,3,3]).mode()

0    3
dtype: int64

## 편차 (deviation): 각 데이터가 평균으로부터 어느 정도 떨어져 있는가를 나타내는 지표

In [42]:
mean = np.mean(scores)
mean

53.0

In [43]:
deviation = scores - mean
deviation

array([-11.000, 16.000, 3.000, -12.000, 4.000])

In [44]:
np.mean(deviation ** 2)

109.2

In [45]:
np.var(scores)

109.2

In [46]:
df2['english'].var()

136.5

- 분산에는 표본분산과 불편분산의 두 종류가 있다.
- Numpy는 표본분산을 기본 분산으로 사용
- Pandas는 불편분산을 기본 분산으로 사용
- 국내 통계학에서는 불편분산을 기본 분산으로 채택

# 표준편차(standard devation) : 분산에 제곱근을 취한 값

In [47]:
np.sqrt(np.var(scores, ddof=0))

10.449880382090505

In [48]:
np.std(scores, ddof=0)

10.449880382090505

## 범위(range) : 데이터의 최대값과 최소값만으로 산포도를 표현하는 방법
- 분산이나 표준편차와 달리 데이터 전체를 보는 것은 아니다.
- 최대값과 최소값의 차이가 크면 산포도가 크기, 그 차이가 작으면 산포도도 작다는 의미
- 이상치가 있을경우 대푯값으로 사용할 수 있다.

In [49]:
np.max(scores) - np.min(scores)

28

# 사분위수
- 전체 데이터의 분포를 파악할 때 사용된다.

In [50]:
pd.Series(scores).describe()

count    5.000
mean    53.000
std     11.683
min     41.000
25%     42.000
50%     56.000
75%     57.000
max     69.000
dtype: float64

In [51]:
q1 = np.percentile(scores, 25)
q3 = np.percentile(scores, 75)
iqr = q3 - q1
iqr

15.0