<a href="https://colab.research.google.com/github/fightmeat/Machine_Leaning/blob/main/NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [81]:
import numpy as np
import pandas as pd

In [7]:
data = [[1,2,3],[4,5,6],[7,8,9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
type(a)

numpy.ndarray

In [8]:
a.dtype

dtype('int64')

In [10]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [12]:
a = a.astype(np.float32) # a = a.stype('float') 도 형변환 가능
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [14]:
a[0]

array([1., 2., 3.], dtype=float32)

In [13]:
a[0][1]

2.0

In [15]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

- 개수가 같아야함

In [16]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(1, 13).reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
np.arange(1, 13).reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [20]:
np.nan * 10

nan

In [22]:
a[0][1] = np.nan

In [23]:
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [24]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- int 는 Nan을 사용할수없다. float만 사용가능

In [25]:
a[0][1] = np.nan

ValueError: ignored

In [27]:
a = np.linspace(1, 10, 20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## 연산

In [28]:
data = np.arange(1, 10).reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- 파이썬에서는 리스트 끼리 연결되지만 넘파이에서는 연산이 가능하다.

In [30]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [29]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
data - data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

- 넘파이로 곱과 나누기도 가능하지만 각 원소들 끼리의 곱과 나누기이다.

In [32]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [33]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- 행렬의 곱은 다른방식을 사용해줘야한다.

In [35]:
np.dot(data, data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [36]:
data@data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## 차원

In [42]:
# 0차원 : 스칼라
a = np.array(1)
a
a.shape

()

In [43]:
a.ndim

0

In [44]:
# 1차원 : 벡터
a = np.array([1])
a
a.shape

(1,)

In [45]:
a.ndim

1

In [47]:
# 1차원 : 벡터
a = np.array([1,2,3,4,5])
a
a.shape

(5,)

In [48]:
a.ndim

1

In [50]:
# 2차원 : 메트릭스
a = np.array([[1,2,3],[4,5,6]])
a
a.shape

(2, 3)

In [51]:
a.ndim

2

In [52]:
# 2차원 : 메트릭스
a = np.array([[1]])
a
a.shape

(1, 1)

In [54]:
# 3차원 : 3차원 이상의 다차원의 행렬을 Tensor라고 합니다!
# Tensorflow가 다차원행렬을 연산해서 어떤 결과를 도출해내는것
a = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,2]]])
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11,  2]]])

In [55]:
a.shape

(2, 3, 2)

In [57]:
a.ndim

3

## matrix의 유형

In [58]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [59]:
b = np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
b = np.ones(12).reshape(2,3,2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [61]:
c = np.zeros(12).reshape(2,3,2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [62]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
e = np.zeros([3,4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
e = np.zeros([3,4,2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

- empty는 0에 가까운값을 채워준다.

In [65]:
f = np.empty([2,3])
f

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [66]:
g = np.full((3,4), 1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [67]:
h = np.linspace(2, 10, 6)
h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

- linspace 2부터 10까지 6개를 만들고 동등한 간격으로 만들어준다.

## 집계 함수

In [68]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
a[0][0] = 100

In [70]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [71]:
a[0, 1] = 1000

In [72]:
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [73]:
np.mean(a)

114.4

- 중앙값

In [74]:
np.median(a)

6.5

- 표준편차

In [75]:
np.std(a)

296.5485457728633

- 분산

In [76]:
np.var(a)

87941.04

- 합계

In [77]:
np.sum(a)

1144

- 그냥 sum은 axis=0인 np.sum과 같고 열방향으로 더하기구나

In [78]:
sum(a)

array([ 105, 1006,    9,   11,   13])

In [79]:
np.sum(a, axis=0)

array([ 105, 1006,    9,   11,   13])

- axis=1이면 행방향 더하기구나

In [80]:
np.sum(a, axis=1)

array([1109,   35])

# Pandas

In [82]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [84]:
a = pd.Series(data, index=['a','b','c','d','e'])
a

a    0
b    1
c    2
d    3
e    4
dtype: int64

- index를 설정안하면 0부터 4까지 자동으로 할당되는모습을 볼수있다.

In [85]:
b = pd.Series(data)
b

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [86]:
data = np.arange(0, 50, 10)
data

array([ 0, 10, 20, 30, 40])

In [87]:
data = pd.Series(data, index=['a','b','c','d','e'])
data

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [88]:
a = pd.Series(data, index=['a','b','c','d','e'])
a

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [90]:
data = np.arange(0, 50, 10)
data

array([ 0, 10, 20, 30, 40])

In [91]:
b = pd.Series(data)
b

0     0
1    10
2    20
3    30
4    40
dtype: int64

In [92]:
a['b']

10

- 명시적 인덱스 로케이션

In [93]:
a.loc['b']

10

- 인덱스 로케이션

In [94]:
a.iloc[1]

10

## 산술연산

In [95]:
a

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [96]:
a + 10

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [97]:
a - 10

a   -10
b     0
c    10
d    20
e    30
dtype: int64

In [98]:
a * 10

a      0
b    100
c    200
d    300
e    400
dtype: int64

In [99]:
a ** 2

a       0
b     100
c     400
d     900
e    1600
dtype: int64

In [100]:
a / 5

a    0.0
b    2.0
c    4.0
d    6.0
e    8.0
dtype: float64

- 나누기를 하니 float로 변환되었다.

In [102]:
a // 5

a    0
b    2
c    4
d    6
e    8
dtype: int64

In [103]:
a % 3

a    0
b    1
c    2
d    0
e    1
dtype: int64

In [104]:
a

a     0
b    10
c    20
d    30
e    40
dtype: int64

In [105]:
a > 15

a    False
b    False
c     True
d     True
e     True
dtype: bool

- boolean 인덱싱

In [106]:
a[a>15]

c    20
d    30
e    40
dtype: int64

## 집계함수

In [107]:
a.add(100)

a    100
b    110
c    120
d    130
e    140
dtype: int64

In [108]:
a.sub(100)

a   -100
b    -90
c    -80
d    -70
e    -60
dtype: int64

In [109]:
a.mul(100)

a       0
b    1000
c    2000
d    3000
e    4000
dtype: int64

In [110]:
a.div(100)

a    0.0
b    0.1
c    0.2
d    0.3
e    0.4
dtype: float64

In [111]:
a.mod(3)

a    0
b    1
c    2
d    0
e    1
dtype: int64

In [112]:
a.min()

0

In [113]:
a.max()

40

In [114]:
a.sum()

100

In [115]:
a.mean()

20.0

In [116]:
a.median()

20.0

In [117]:
a.std()

15.811388300841896

In [118]:
a.var()

250.0

## DataFrame

- 엑셀이나 스프레드시트라고 이해하면 편하다.

In [119]:
rawData = np.random.randint(50, 100, size=(4,3))
rawData

array([[87, 61, 84],
       [81, 99, 74],
       [99, 73, 70],
       [84, 89, 68]])

In [144]:
df = pd.DataFrame(rawData, index=['1반','2반','1반','2반'],
                  columns=['국','영','수'])

In [121]:
df

국   영   수
1반  87  61  84
2반  81  99  74
1반  99  73  70
2반  84  89  68

In [122]:
df['국']

1반    87
2반    81
1반    99
2반    84
Name: 국, dtype: int64

- 0을 하면 에러가 난다.

In [123]:
df[0]

KeyError: ignored

In [127]:
df['평균'] = round((df['국'] + df['영']+ df['수']) / 3, 2)
df

국   영   수     평균
1반  87  61  84  77.33
2반  81  99  74  84.67
1반  99  73  70  80.67
2반  84  89  68  80.33

In [128]:
df['na'] = np.nan
df

국   영   수     평균  na
1반  87  61  84  77.33 NaN
2반  81  99  74  84.67 NaN
1반  99  73  70  80.67 NaN
2반  84  89  68  80.33 NaN

In [129]:
del df ['na']

In [130]:
df

국   영   수     평균
1반  87  61  84  77.33
2반  81  99  74  84.67
1반  99  73  70  80.67
2반  84  89  68  80.33

- boolean 인덱싱

In [132]:
df[df['평균']> 80]

국   영   수     평균
2반  81  99  74  84.67
1반  99  73  70  80.67
2반  84  89  68  80.33

In [133]:
df = df.drop(['평균'], axis='columns')

In [134]:
df

국   영   수
1반  87  61  84
2반  81  99  74
1반  99  73  70
2반  84  89  68

## 결측값 처리

In [136]:
df = df.astype('float64')
df

국     영     수
1반  87.0  61.0  84.0
2반  81.0  99.0  74.0
1반  99.0  73.0  70.0
2반  84.0  89.0  68.0

In [137]:
df['수'][2]

70.0

In [146]:
df['수'][2] = np.nan
df

국   영     수
1반  87  61  84.0
2반  81  99  74.0
1반  99  73   NaN
2반  84  89  68.0

- 원본수정은 inplace

In [142]:
df.dropna(axis=0,inplace=True) # inplace = True

In [143]:
df

국     영     수
1반  87.0  61.0  84.0
2반  81.0  99.0  74.0
2반  84.0  89.0  68.0

- 다시 위에 있는 raw 실행후 결측값 적용후 아래로

In [147]:
df

국   영     수
1반  87  61  84.0
2반  81  99  74.0
1반  99  73   NaN
2반  84  89  68.0

In [148]:
df.dropna(axis=1)

국   영
1반  87  61
2반  81  99
1반  99  73
2반  84  89

In [149]:
df.fillna('hello')

국   영      수
1반  87  61   84.0
2반  81  99   74.0
1반  99  73  hello
2반  84  89   68.0

In [150]:
df.fillna(0)

국   영     수
1반  87  61  84.0
2반  81  99  74.0
1반  99  73   0.0
2반  84  89  68.0

In [153]:
df.fillna(df.mean())

국   영          수
1반  87  61  84.000000
2반  81  99  74.000000
1반  99  73  75.333333
2반  84  89  68.000000

## MultiIndex

In [154]:
df

국   영     수
1반  87  61  84.0
2반  81  99  74.0
1반  99  73   NaN
2반  84  89  68.0

In [155]:
df.T

1반    2반    1반    2반
국  87.0  81.0  99.0  84.0
영  61.0  99.0  73.0  89.0
수  84.0  74.0   NaN  68.0

In [156]:
df

국   영     수
1반  87  61  84.0
2반  81  99  74.0
1반  99  73   NaN
2반  84  89  68.0

In [157]:
df.index = [['1학년','1학년','2학년','2학년'],['1반','2반','1반','2반']]
df

국   영     수
1학년 1반  87  61  84.0
    2반  81  99  74.0
2학년 1반  99  73   NaN
    2반  84  89  68.0

In [158]:
df.columns = [['언어','언어','수리'],['국','영','수']]
df

언어        수리
         국   영     수
1학년 1반  87  61  84.0
    2반  81  99  74.0
2학년 1반  99  73   NaN
    2반  84  89  68.0

In [161]:
df['언어']['국']

1학년  1반    87
     2반    81
2학년  1반    99
     2반    84
Name: 국, dtype: int64

In [162]:
df.iloc[0]

언어  국    87.0
    영    61.0
수리  수    84.0
Name: (1학년, 1반), dtype: float64

In [163]:
df.loc['1학년']

언어        수리
     국   영     수
1반  87  61  84.0
2반  81  99  74.0

In [164]:
df.loc['1학년'].loc['1반']

언어  국    87.0
    영    61.0
수리  수    84.0
Name: 1반, dtype: float64

## 데이터 사전 분석

In [165]:
df

언어        수리
         국   영     수
1학년 1반  87  61  84.0
    2반  81  99  74.0
2학년 1반  99  73   NaN
    2반  84  89  68.0

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('1학년', '1반') to ('2학년', '2반')
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   (언어, 국)  4 non-null      int64  
 1   (언어, 영)  4 non-null      int64  
 2   (수리, 수)  3 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 384.0+ bytes


In [169]:
df.head(2)

언어        수리
         국   영     수
1학년 1반  87  61  84.0
    2반  81  99  74.0

In [170]:
df.tail(2)

언어        수리
         국   영     수
2학년 1반  99  73   NaN
    2반  84  89  68.0

In [171]:
df.dtypes

언어  국      int64
    영      int64
수리  수    float64
dtype: object

In [172]:
df.describe()

언어                    수리
               국          영          수
count   4.000000   4.000000   3.000000
mean   87.750000  80.500000  75.333333
std     7.889867  16.842407   8.082904
min    81.000000  61.000000  68.000000
25%    83.250000  70.000000  71.000000
50%    85.500000  81.000000  74.000000
75%    90.000000  91.500000  79.000000
max    99.000000  99.000000  84.000000

In [173]:
df.isnull()

언어            수리
            국      영      수
1학년 1반  False  False  False
    2반  False  False  False
2학년 1반  False  False   True
    2반  False  False  False

In [174]:
df.isnull().sum()

언어  국    0
    영    0
수리  수    1
dtype: int64

## 값의 연결

- 아래 추가는 append
- 옆 추가는 concat

In [175]:
a = pd.DataFrame(np.arange(1,10).reshape(3,3))
a

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [176]:
b = pd.Series(np.arange(10,40,10))

In [177]:
b

0    10
1    20
2    30
dtype: int64

In [178]:
pd.concat([a,b], axis=1)

0  1  2   0
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

- 근데 0 1 2 0이니까 3으로 바꾸고 싶다.

In [179]:
pd.concat([a,b], axis=1, ignore_index=True)

0  1  2   3
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [180]:
a.append(b, ignore_index=True)

<ipython-input-180-9477ed419ed4>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  a.append(b, ignore_index=True)


0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  20  30